/**
 * Ghost Order Book — Midnight TestNet Deployment Script
 *
 * Prerequisites:
 *   1. Compile the contract first (or use pre-built from ./build):
 *        npx @midnight-ntwrk/compact-compiler ../contracts/ghost_liquidity.compact --output ./build
 *   2. Set env vars (or create a .env file):
 *        MIDNIGHT_SEED_PHRASE   — 24-word BIP-39 mnemonic for your TestNet wallet
 *        MIDNIGHT_NETWORK       — "testnet" | "devnet" (default: testnet)
 *
 * Run:
 *   npx ts-node --esm deploy.ts
 */

// Network identifiers for Midnight
const NetworkId = {
  TestNet: 'testnet',
  DevNet: 'devnet',
} as const;

// ── Network endpoints ────────────────────────────────────────────────────────
const NETWORKS: Record<string, { node: string; indexer: string; prover: string }> = {
  testnet: {
    node:    'https://rpc.testnet.midnight.network',
    indexer: 'https://indexer.testnet.midnight.network/api/v1/graphql',
    prover:  'https://prover.testnet.midnight.network',
  },
  devnet: {
    node:    'https://rpc.devnet.midnight.network',
    indexer: 'https://indexer.devnet.midnight.network/api/v1/graphql',
    prover:  'https://prover.devnet.midnight.network',
  },
};

async function main() {
  const network = (process.env.MIDNIGHT_NETWORK ?? 'testnet') as keyof typeof NETWORKS;
  const seedPhrase = process.env.MIDNIGHT_SEED_PHRASE;

  if (!seedPhrase) {
    console.error('❌  MIDNIGHT_SEED_PHRASE env var is required.');
    console.error('    Export your 24-word TestNet wallet mnemonic:');
    console.error('    set MIDNIGHT_SEED_PHRASE=word1 word2 ... word24');
    process.exit(1);
  }

  const endpoints = NETWORKS[network];
  if (!endpoints) {
    console.error(`❌  Unknown network "${network}". Use "testnet" or "devnet".`);
    process.exit(1);
  }

  console.log(`\n🌙  Ghost Order Book — Midnight Deployment`);
  console.log(`    Network  : ${network}`);
  console.log(`    Node     : ${endpoints.node}`);
  console.log(`    Indexer  : ${endpoints.indexer}`);
  console.log(`    Prover   : ${endpoints.prover}\n`);

  // ── Dynamic imports (ESM packages) ────────────────────────────────────────
  const { WalletBuilder }       = await import('@midnight-ntwrk/wallet');
  const { indexerPublicDataProvider } = await import('@midnight-ntwrk/midnight-js-contracts');
  const { httpClientProofProvider }   = await import('@midnight-ntwrk/wallet-sdk-prover-client');
  const { levelPrivateStateProvider } = await import('@midnight-ntwrk/wallet-sdk');

  // ── Build wallet from seed phrase ─────────────────────────────────────────
  console.log('🔑  Restoring wallet from seed phrase...');
  const networkId = network === 'testnet' ? NetworkId.TestNet : NetworkId.DevNet;
  const wallet = await WalletBuilder.restore(
    endpoints.node,
    endpoints.indexer,
    endpoints.prover,
    seedPhrase,
    networkId,
  );

  await wallet.start();

  const state = await wallet.state();
  console.log(`✅  Wallet ready`);
  console.log(`    Address : ${state.address}`);
  console.log(`    Balance : ${state.balances?.dust ?? 0} DUST\n`);

  // ── Load compiled contract artifacts ──────────────────────────────────────
  console.log('📦  Loading compiled contract artifacts...');
  let contract: any;
  try {
    // These are generated by: npx @midnight-ntwrk/compact-compiler
    const { GhostLiquidityContract } = await import('./build/ghost_liquidity/index.js');
    contract = new GhostLiquidityContract();
  } catch {
    console.error('❌  Compiled contract not found at ./build/ghost_liquidity/index.js');
    console.error('    Run the compiler first:');
    console.error('    npx @midnight-ntwrk/compact-compiler ../contracts/ghost_liquidity.compact --output ./build');
    process.exit(1);
  }

  // ── Deploy contract ────────────────────────────────────────────────────────
  console.log('🚀  Deploying ghost_liquidity contract to Midnight TestNet...');

  const providers = {
    privateStateProvider: levelPrivateStateProvider('./private-state-db'),
    publicDataProvider:   indexerPublicDataProvider(endpoints.indexer),
    proofProvider:        httpClientProofProvider(endpoints.prover),
    walletProvider:       wallet,
    midnightProvider:     wallet,
  };

  const deployedContract = await contract.deploy(providers, {
    // Initial ledger state — empty commitment root and nullifier
    initialState: {
      root:      new Uint8Array(32),
      nullifier: new Uint8Array(32),
    },
  });

  const contractAddress = deployedContract.deployTxData.public.contractAddress;

  console.log(`\n✅  Contract deployed successfully!`);
  console.log(`    Contract Address : ${contractAddress}`);
  console.log(`    Tx Hash          : ${deployedContract.deployTxData.public.txHash}\n`);

  // ── Write deployment info ──────────────────────────────────────────────────
  const deploymentInfo = {
    network,
    contractAddress,
    txHash: deployedContract.deployTxData.public.txHash,
    deployedAt: new Date().toISOString(),
    endpoints,
  };

  const { writeFileSync } = await import('fs');
  writeFileSync('./deployment.json', JSON.stringify(deploymentInfo, null, 2));
  console.log('📄  Deployment info saved to ./deploy/deployment.json');
  console.log('\n    Next step: set NEXT_PUBLIC_CONTRACT_ADDRESS in frontend/.env.local');
  console.log(`    NEXT_PUBLIC_CONTRACT_ADDRESS=${contractAddress}\n`);

  await wallet.close();
}

main().catch((err) => {
  console.error('❌  Deployment failed:', err);
  process.exit(1);
});
